name: npt
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8
  - pytorch
  - torchvision
  - pip
  - pip:
    - wandb
    - scikit-learn
    - pandas
    - pycodestyle
    - dotmap
    - line-profiler
    - tqdm
    - pytorch-lightning
    - patool
    - wget
    - scikit-optimize
    - xgboost
    - catboost
    - transformers
    - pytorch-tabnet
    - numba
    - ogb
    - memory-profiler
    - seaborn
    - tensorboardX
    - seaborn
    - fairseq
    - dotmap
    - tabnet
    - lightgbm
    - jupyterlab
    - notebook
    - matplotlib
    - qhoptim
    - torchvision
    - gpytorch