wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.19
    cli_version: 0.16.5
    framework: lightgbm
    huggingface_version: 4.39.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1719238375.0
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 6
      - 7
      - 8
      - 11
      - 41
      - 49
      - 50
      - 53
      - 55
      - 64
      3:
      - 13
      - 23
      4: 3.8.19
      5: 0.16.5
      6: 4.39.3
      8:
      - 5
      13: darwin-arm64
