wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.19
    cli_version: 0.16.5
    framework: lightgbm
    huggingface_version: 4.39.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1718811625.0
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 6
      - 7
      - 8
      - 11
      - 41
      - 49
      - 50
      - 53
      - 55
      - 64
      2:
      - 1
      - 2
      - 3
      - 5
      - 6
      - 7
      - 8
      - 11
      - 41
      - 49
      - 50
      - 53
      - 55
      - 64
      3:
      - 13
      - 23
      4: 3.8.19
      5: 0.16.5
      6: 4.39.3
      8:
      - 4
      - 5
      13: darwin-arm64
entity:
  desc: null
  value: null
project:
  desc: null
  value: default
wandb_dir:
  desc: null
  value: ./
data_path:
  desc: null
  value: data
data_set:
  desc: null
  value: ode
data_loader_nprocs:
  desc: null
  value: 0
data_set_on_cuda:
  desc: null
  value: false
data_force_reload:
  desc: null
  value: false
data_log_mem_usage:
  desc: null
  value: false
data_clear_tmp_files:
  desc: null
  value: false
data_dtype:
  desc: null
  value: float32
exp_device:
  desc: null
  value: cpu
exp_azure_sweep:
  desc: null
  value: false
exp_test_equivariance:
  desc: null
  value: false
exp_show_empirical_label_dist:
  desc: null
  value: false
exp_smoke_test:
  desc: null
  value: false
exp_name:
  desc: null
  value: s2bplfco
exp_group:
  desc: null
  value: null
np_seed:
  desc: null
  value: 42
torch_seed:
  desc: null
  value: 42
baseline_seed:
  desc: null
  value: 42
exp_use_cuda:
  desc: null
  value: true
exp_n_runs:
  desc: null
  value: 1
exp_batch_size:
  desc: null
  value: -1
exp_batch_mode_balancing:
  desc: null
  value: true
exp_batch_class_balancing:
  desc: null
  value: false
exp_minibatch_sgd:
  desc: null
  value: true
exp_val_perc:
  desc: null
  value: 0.1
exp_test_perc:
  desc: null
  value: 0.2
exp_num_total_steps:
  desc: null
  value: 100000.0
exp_patience:
  desc: null
  value: -1
exp_checkpoint_setting:
  desc: null
  value: best_model
exp_cache_cadence:
  desc: null
  value: 1
exp_load_from_checkpoint:
  desc: null
  value: false
exp_print_every_nth_forward:
  desc: null
  value: false
exp_eval_every_n:
  desc: null
  value: 5
exp_eval_every_epoch_or_steps:
  desc: null
  value: epochs
exp_eval_test_at_end_only:
  desc: null
  value: false
exp_artificial_missing:
  desc: null
  value: 0
exp_optimizer:
  desc: null
  value: lookahead_lamb
exp_lookahead_update_cadence:
  desc: null
  value: 6
exp_optimizer_warmup_proportion:
  desc: null
  value: 0.7
exp_optimizer_warmup_fixed_n_steps:
  desc: null
  value: 10000
exp_lr:
  desc: null
  value: 0.001
exp_scheduler:
  desc: null
  value: flat_and_anneal
exp_gradient_clipping:
  desc: null
  value: 1.0
exp_weight_decay:
  desc: null
  value: 0
exp_tradeoff:
  desc: null
  value: 0.5
exp_tradeoff_annealing:
  desc: null
  value: cosine
exp_tradeoff_annealing_proportion:
  desc: null
  value: 1
mp_distributed:
  desc: null
  value: false
mp_nodes:
  desc: null
  value: 1
mp_gpus:
  desc: null
  value: 1
mp_nr:
  desc: null
  value: 0
mp_no_sync:
  desc: null
  value: -1
mp_bucket_cap_mb:
  desc: null
  value: 25
verbose:
  desc: null
  value: false
debug_leakage:
  desc: null
  value: false
debug_label_leakage:
  desc: null
  value: false
debug_row_interactions:
  desc: null
  value: false
debug_eval_row_interactions:
  desc: null
  value: false
debug_eval_row_interactions_timer:
  desc: null
  value: null
debug_row_interactions_mode:
  desc: null
  value: null
debug_no_stratify:
  desc: null
  value: false
debug_corrupt_standard_dataset_ablate_shuffle:
  desc: null
  value: false
model_class:
  desc: null
  value: NPT
sklearn_hyper_search:
  desc: null
  value: Grid
sklearn_model:
  desc: null
  value: All
sklearn_verbose:
  desc: null
  value: 1
sklearn_n_jobs:
  desc: null
  value: -1
sklearn_val_final_fit:
  desc: null
  value: false
model_is_semi_supervised:
  desc: null
  value: true
model_dtype:
  desc: null
  value: float32
model_amp:
  desc: null
  value: false
model_feature_type_embedding:
  desc: null
  value: true
model_feature_index_embedding:
  desc: null
  value: true
model_bert_augmentation:
  desc: null
  value: true
model_bert_mask_percentage:
  desc: null
  value: 0.9
model_augmentation_bert_mask_prob:
  desc: null
  value:
    train: 0.15
    val: 0.0
    test: 0.0
model_label_bert_mask_prob:
  desc: null
  value:
    train: 1
    val: 1
    test: 1
model_embedding_layer_norm:
  desc: null
  value: false
model_att_block_layer_norm:
  desc: null
  value: true
model_layer_norm_eps:
  desc: null
  value: 1.0e-12
model_att_score_norm:
  desc: null
  value: softmax
model_pre_layer_norm:
  desc: null
  value: true
model_hidden_dropout_prob:
  desc: null
  value: 0.1
model_att_score_dropout_prob:
  desc: null
  value: 0.1
model_hybrid_debug:
  desc: null
  value: false
model_checkpoint_key:
  desc: null
  value: null
model_dim_hidden:
  desc: null
  value: 128
model_num_heads:
  desc: null
  value: 8
model_sep_res_embed:
  desc: null
  value: true
model_stacking_depth:
  desc: null
  value: 8
model_mix_heads:
  desc: null
  value: true
model_rff_depth:
  desc: null
  value: 1
model_image_n_patches:
  desc: null
  value: false
model_image_patch_type:
  desc: null
  value: linear
model_image_n_channels:
  desc: null
  value: 3
model_image_share_embed:
  desc: null
  value: true
model_image_n_classes:
  desc: null
  value: 10
model_image_random_crop_and_flip:
  desc: null
  value: true
metrics_auroc:
  desc: null
  value: true
viz_att_maps:
  desc: null
  value: false
viz_att_maps_save_path:
  desc: null
  value: data/attention_maps
cv_index:
  desc: null
  value: 0
